name: debug_friend
description: Flutter debug helper widget with device info, common and custom actions.
version: 0.3.0
homepage: https://github.com/Frezyx/debug_friend

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: ^3.2.0
  package_info_plus: ^1.3.0
  path_provider: ^2.0.8
  lint: ^1.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: