name: debug_friend
description: Flutter debug helper widget with device info, common and custom actions.
version: 1.0.0
homepage: https://github.com/Frezyx/debug_friend

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: ^4.1.2
  package_info_plus: ^1.4.3+1
  path_provider: ^2.0.11
  lint: ^1.10.0
  talker: ^1.3.0+1
  talker_flutter: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: